# Site settings
title: DATAVERSO
description: Isso nao eh pra ser um blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: http://dataverso.com.br


# User settings
username: DATAVERSO
user_description: DataVerso é uma empresa de ciência de dados com o foco em implementações de soluções de Inteligência Artificial e Machine Learning para melhorar os processos de tomadas de decisões em empresas e negócios. Nossa missão é trazer valor através da otimização de diversos processos inerentes ao cotidiano das empresas, tais como People Analytics (RH), análise e projeção de vendas, identificação de tendências, análise de marketing e análise financeira. Nossa empresa utiliza as melhores ferramentas do mercado e conta com especialistas para entregar soluções robustas e confiáveis para sustentar tomadas de decisões ótimas e inovadoras.
user_title: Data Driven Solutions
email: pedrolealdino@gmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "G-1B28NXZHJ5"

exclude: ['package.json', 'src' , 'node_modules']
